# Generated by Django 3.1.7 on 2021-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('prefix_id', models.PositiveIntegerField(verbose_name='Префикс')),
                ('name', models.CharField(max_length=300, verbose_name='Идентификатор товара')),
                ('fake_data', models.TextField(verbose_name='Данные по товару (предварительно)')),
            ],
        ),
    ]
