# Generated by Django 3.2.6 on 2021-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_marketdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketdata',
            name='fake_data',
        ),
        migrations.AddField(
            model_name='marketdata',
            name='json_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные по товару'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='name',
            field=models.CharField(help_text='Например "Glove Case"', max_length=300, verbose_name='Идентификатор товара'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='prefix_id',
            field=models.PositiveIntegerField(help_text='Например, 730 из ссылки', verbose_name='Префикс'),
        ),
    ]
