# Generated by Django 3.2.6 on 2021-08-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0004_markerdatarecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdata',
            options={'verbose_name': 'Данные по товару', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='markerdatarecord',
            name='market_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='marketdata.marketdata', verbose_name='Товар в магазине'),
        ),
        migrations.AlterField(
            model_name='markerdatarecord',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Цена'),
        ),
    ]
