# Generated by Django 3.2.6 on 2021-08-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_auto_20210807_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='markerdatarecord',
            name='count',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='markerdatarecord',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Цена'),
        ),
    ]
