# Generated by Django 3.2.6 on 2021-08-29 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0006_auto_20210807_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketdata',
            options={'ordering': ('id',), 'verbose_name': 'Данные по товару', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='marketdata',
            name='date_start_trade',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала торгов'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='last_data_expanded',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата последней информации'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='last_loaded',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата последнего обновления информации'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='last_meta_calculated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата последней пересчёта мета-информации'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='preview_data',
            field=models.JSONField(blank=True, null=True, verbose_name='До 10 точек для превью'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='rating',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Рейтинг'),
        ),
    ]
